/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;
import com.boletos.boletosapiu.model.DetalleVenta;
import com.boletos.boletosapiu.model.Partido;
import com.boletos.boletosapiu.model.Usuario;
import com.boletos.boletosapiu.model.Venta;
import com.boletos.boletosapiu.service.DetalleVentaService;
import com.boletos.boletosapiu.service.PartidoService;
import com.boletos.boletosapiu.service.VentaService;
import com.boletos.boletosapiu.utils.CustomScrollBarUI;
import com.boletos.boletosapiu.utils.GradientPanelBoletos;
import com.boletos.boletosapiu.utils.RoundedPanel;
import com.boletos.boletosapiu.utils.VentaFiltrada;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 *
 * @author AMD 5600G
 */
public class AdminDashboardPanel extends javax.swing.JPanel {

    private mainPanel mainFrame;
    VentaService serviceVentas = new VentaService();
    DetalleVentaService serviceDetalle = new DetalleVentaService();
    PartidoService servicePartido = new PartidoService();
    List<Venta> listaVentas;
    List<DetalleVenta> listaDetalleVentas;
    List<Partido> listaPartidos;
    
    /**
     * Creates new form AdminDashboardPanel
     */
    public AdminDashboardPanel() {
        initComponents();       
    }
    
    public AdminDashboardPanel(mainPanel main) {
        initComponents();
        this.mainFrame = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        lblNombreApellido = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblPartidos = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        LabelFotoUsuario = new javax.swing.JLabel();
        scrollDashboard = new javax.swing.JScrollPane();
        Dashboard = new GradientPanelBoletos(
            java.awt.Color.decode("#A1A6AD"),  // color 1
            java.awt.Color.decode("#021E45")
        );
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(30);
        jLabel8 = new javax.swing.JLabel();
        lblVentasDiarias = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(30);
        jLabel10 = new javax.swing.JLabel();
        lblVentasTotales = new javax.swing.JLabel();
        jPanel6 = new RoundedPanel(30);
        jLabel12 = new javax.swing.JLabel();
        lblBoletosDiarios = new javax.swing.JLabel();
        pnlBarChart = new javax.swing.JPanel();
        pnlLineChart = new javax.swing.JPanel();

        MainPanel.setPreferredSize(new java.awt.Dimension(1150, 630));
        MainPanel.setLayout(new java.awt.BorderLayout());

        Menu.setBackground(new java.awt.Color(35, 35, 35));
        Menu.setPreferredSize(new java.awt.Dimension(250, 600));

        lblNombreApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreApellido.setText("Nombre + Apellido");
        lblNombreApellido.setPreferredSize(new java.awt.Dimension(250, 30));

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("NOMBRE DE USUARIO");
        lblUserName.setPreferredSize(new java.awt.Dimension(250, 30));

        lblVentas.setBackground(new java.awt.Color(2, 30, 69));
        lblVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales.png"))); // NOI18N
        lblVentas.setText("RESUMEN DE VENTAS");
        lblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentas.setPreferredSize(new java.awt.Dimension(250, 30));
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentasMouseExited(evt);
            }
        });

        lblPartidos.setBackground(new java.awt.Color(2, 30, 69));
        lblPartidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPartidos.setForeground(new java.awt.Color(255, 255, 255));
        lblPartidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soccer.png"))); // NOI18N
        lblPartidos.setText("PARTIDOS");
        lblPartidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPartidos.setPreferredSize(new java.awt.Dimension(250, 30));
        lblPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPartidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPartidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPartidosMouseExited(evt);
            }
        });

        lblUsers.setBackground(new java.awt.Color(2, 30, 69));
        lblUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        lblUsers.setText("USUARIOS");
        lblUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsers.setPreferredSize(new java.awt.Dimension(250, 30));
        lblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsersMouseExited(evt);
            }
        });

        lblDashboard.setBackground(new java.awt.Color(2, 30, 69));
        lblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        lblDashboard.setText("DASHBOARD");
        lblDashboard.setOpaque(true);
        lblDashboard.setPreferredSize(new java.awt.Dimension(250, 30));

        lblCerrarSesion.setBackground(new java.awt.Color(2, 30, 69));
        lblCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log-out-30.png"))); // NOI18N
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.setPreferredSize(new java.awt.Dimension(250, 30));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        LabelFotoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        LabelFotoUsuario.setText("jLabel1");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNombreApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblPartidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(LabelFotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        MainPanel.add(Menu, java.awt.BorderLayout.WEST);

        scrollDashboard.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDashboard.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollDashboard.setPreferredSize(new java.awt.Dimension(900, 1070));

        Dashboard.setPreferredSize(new java.awt.Dimension(950, 1068));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dashboard");

        jPanel4.setBackground(new java.awt.Color(2, 30, 69));
        jPanel4.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ventas de hoy");

        lblVentasDiarias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVentasDiarias.setForeground(new java.awt.Color(255, 255, 255));
        lblVentasDiarias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasDiarias.setText("Q 100.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblVentasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(2, 30, 69));
        jPanel5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ventas totales");

        lblVentasTotales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVentasTotales.setForeground(new java.awt.Color(255, 255, 255));
        lblVentasTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotales.setText("Q 1,000,000.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentasTotales, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblVentasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(2, 30, 69));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 32));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Boletos vendidos hoy");

        lblBoletosDiarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBoletosDiarios.setForeground(new java.awt.Color(255, 255, 255));
        lblBoletosDiarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBoletosDiarios.setText("1000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBoletosDiarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(lblBoletosDiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBarChartLayout = new javax.swing.GroupLayout(pnlBarChart);
        pnlBarChart.setLayout(pnlBarChartLayout);
        pnlBarChartLayout.setHorizontalGroup(
            pnlBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBarChartLayout.setVerticalGroup(
            pnlBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLineChartLayout = new javax.swing.GroupLayout(pnlLineChart);
        pnlLineChart.setLayout(pnlLineChartLayout);
        pnlLineChartLayout.setHorizontalGroup(
            pnlLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLineChartLayout.setVerticalGroup(
            pnlLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLineChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        scrollDashboard.setViewportView(Dashboard);

        MainPanel.add(scrollDashboard, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseEntered
        lblVentas.setOpaque(true);
        lblVentas.repaint();
    }//GEN-LAST:event_lblVentasMouseEntered

    private void lblPartidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPartidosMouseEntered
        lblPartidos.setOpaque(true);
        lblPartidos.repaint();
    }//GEN-LAST:event_lblPartidosMouseEntered

    private void lblUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseEntered
        lblUsers.setOpaque(true);
        lblUsers.repaint();
    }//GEN-LAST:event_lblUsersMouseEntered

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        lblCerrarSesion.setOpaque(true);
        lblCerrarSesion.repaint();
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseExited
        lblVentas.setOpaque(false);
        lblVentas.repaint();
    }//GEN-LAST:event_lblVentasMouseExited

    private void lblPartidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPartidosMouseExited
        lblPartidos.setOpaque(false);
        lblPartidos.repaint();
    }//GEN-LAST:event_lblPartidosMouseExited

    private void lblUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseExited
        lblUsers.setOpaque(false);
        lblUsers.repaint();
    }//GEN-LAST:event_lblUsersMouseExited

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        lblCerrarSesion.setOpaque(false);
        lblCerrarSesion.repaint();
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        mainFrame.ShowPanel("login");
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        mainFrame.loadDetalleVenta(listaVentas, listaDetalleVentas, listaPartidos);
    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseClicked
        mainFrame.loadUsuariosPanel();
    }//GEN-LAST:event_lblUsersMouseClicked

    private void lblPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPartidosMouseClicked
        mainFrame.loadPartidosPanel();
    }//GEN-LAST:event_lblPartidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel LabelFotoUsuario;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblBoletosDiarios;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblNombreApellido;
    private javax.swing.JLabel lblPartidos;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblVentasDiarias;
    private javax.swing.JLabel lblVentasTotales;
    private javax.swing.JPanel pnlBarChart;
    private javax.swing.JPanel pnlLineChart;
    private javax.swing.JScrollPane scrollDashboard;
    // End of variables declaration//GEN-END:variables

    private void setChartColors(JFreeChart chart){
        CategoryPlot plot = chart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        
        // Pintura gradiente en barras
        renderer.setSeriesPaint(0, new GradientPaint(0, 0, new Color(35,35,35), 0, 0, Color.decode("#021E45")));
        
        // Borde en la barra
        renderer.setDrawBarOutline(true);
        renderer.setSeriesOutlinePaint(0, Color.DARK_GRAY);
        
        // Sombras
        renderer.setShadowVisible(true);
        renderer.setShadowPaint(Color.GRAY);
    }
    
    private CategoryDataset crearDatasetLineas(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("MMMM", Locale.ENGLISH);
        LocalDate hoy = LocalDate.now();
        LocalDate lastYear = hoy.minusYears(1);
        List<VentaFiltrada> ventaFiltrada = new ArrayList<>();
        
        for(Venta v: listaVentas){
            LocalDate fechaDeLaVenta = v.getFecha_venta().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if(fechaDeLaVenta.isAfter(lastYear)){
                String fecha = fechaDeLaVenta.format(formato);
                BigDecimal total = v.getTotal_venta();
                String tipoPartido = "";
                int idPartido = 0;
                boolean registroEncontrado = false;
                
                for(DetalleVenta dv : listaDetalleVentas){
                    if(dv.getId_venta() == v.getId_venta()){
                        idPartido = dv.getId_partido();
                        break;
                    }
                }
                
                for(Partido p : listaPartidos){
                    if(p.getId_partido() == idPartido){
                        tipoPartido = p.getCategoria();
                    }
                }
                
                for(VentaFiltrada vf: ventaFiltrada){
                    if(vf.getFecha_venta().equals(fecha) && tipoPartido.equals(vf.getTipo_partido())){            
                        vf.setTotal(vf.getTotal().add(total));
                        registroEncontrado = true;
                    }
                }
                if(!registroEncontrado){
                    VentaFiltrada vFil = new VentaFiltrada(total, fecha, tipoPartido);
                    ventaFiltrada.add(vFil);
                }

            }
        }
        
        ventaFiltrada.sort(Comparator.comparing(
            v -> Month.valueOf(v.getFecha_venta().toUpperCase(Locale.ENGLISH))
        ));
        
       for(VentaFiltrada vf : ventaFiltrada){
            dataset.addValue(vf.getTotal(), vf.getTipo_partido(), vf.getFecha_venta());
        } 
        
        return dataset;
    }
    
    private CategoryDataset crearDatasetBarras(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE", Locale.ENGLISH);
        LocalDate hoy = LocalDate.now();
        LocalDate semanaPasada = hoy.minusWeeks(1);
        HashMap<LocalDate, BigDecimal> ventasPorFecha = new HashMap<>();
        
        for(Venta v : listaVentas){
            LocalDate fechaDeLaVenta = v.getFecha_venta().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if(!fechaDeLaVenta.isBefore(semanaPasada)){  
                ventasPorFecha.merge(fechaDeLaVenta, v.getTotal_venta(), (oldValue, newValue) -> oldValue.add(newValue));
            }
        }
                 
        for(Map.Entry<LocalDate, BigDecimal> entry : ventasPorFecha.entrySet()){   
            dataset.addValue(entry.getValue().doubleValue(), "VentasDiarias", entry.getKey().format(formato));
        }
        
        return dataset;
    }
    
    private void setChartTextColors(JFreeChart chart){
        TextTitle title = chart.getTitle();
        title.setPaint(Color.WHITE);
        
        
        CategoryPlot plot = chart.getCategoryPlot();
        //Color de la parte de abajo, palabra "Día"
        plot.getDomainAxis().setLabelPaint(Color.WHITE);
        //Color de los días de la semana, abajo
        plot.getDomainAxis().setTickLabelPaint(Color.WHITE);
        //Color de la parte de la izquieda, palabra "Total"
        plot.getRangeAxis().setLabelPaint(Color.WHITE);
        //Color de los totales
        plot.getRangeAxis().setTickLabelPaint(Color.WHITE);       
    }
    
    public void cargarAdminDashboard(Usuario user){
        scrollDashboard.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        lblNombreApellido.setText(primerNombre(user.getNombre_completo()));
        lblUserName.setText(user.getNombre_usuario());
        setUserPhoto(user.getNombre_usuario());
               
        cargarListas();    
        llenarLabels();
        cargarGraficaBarras();
        cargarGraficaLineas();
                
    }
    
    private void cargarGraficaBarras(){
        JFreeChart barras = ChartFactory.createBarChart("Ventas semanales", "Día", "Total (Q)", crearDatasetBarras(), PlotOrientation.VERTICAL, false, true, false);
        barras.setBackgroundPaint(new Color(35,35,35));
        setChartColors(barras);
        setChartTextColors(barras);
        ChartPanel chartPanel = new ChartPanel(barras);
        chartPanel.setPreferredSize(new Dimension(860, 400));
        pnlBarChart.setLayout(new BorderLayout());
        pnlBarChart.add(chartPanel, BorderLayout.CENTER);
    }
    
    private void cargarGraficaLineas(){
        JFreeChart lineas = ChartFactory.createLineChart("Ventas de boletos", "Meses", "Boletos vendidos", crearDatasetLineas(), PlotOrientation.VERTICAL, true, true, false);    
        lineas.setBackgroundPaint(new Color(35,35,35));
        setChartTextColors(lineas);       
        ChartPanel chartPanel = new ChartPanel(lineas);
        chartPanel.setPreferredSize(new Dimension(860, 400));   
        pnlLineChart.setLayout(new BorderLayout());
        pnlLineChart.add(chartPanel, BorderLayout.CENTER);      
    }
    
    private static String primerNombre(String nombreCompleto) {
        String nombreSinEspacios = nombreCompleto.trim();
        String[] nombre = nombreSinEspacios.split("\\s+");
    
        return nombre[0] +" "+ nombre[1];
    }
    
    private void cargarListas(){
        try {
            listaVentas = serviceVentas.getVentas();           
        } catch (Exception ex) {
            System.out.println("Error al cargar las ventas: "+ex.getMessage());
        }
        
        try {
            listaDetalleVentas = serviceDetalle.getDetalleVentas();
        } catch (Exception ex) {
            System.out.println("Error al cargar detalle de ventas : "+ex.getMessage());
        }
        
        try {
            listaPartidos = servicePartido.getPartidos();
        } catch (Exception ex) {
            System.out.println("Error al cargar partidos : "+ex.getMessage());
        }
    }
    
    private void llenarLabels(){
        //Para labels de ventas
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date currentDate = new Date();
        String fechaHoy = sdf.format(currentDate);
        BigDecimal ventasDeHoy = BigDecimal.ZERO;
        BigDecimal ventasTotales = BigDecimal.ZERO;
        int totalBoletos = 0;
        
        for(Venta v : listaVentas){     
           if(fechaHoy.equals(sdf.format(v.getFecha_venta()))){
               ventasDeHoy = ventasDeHoy.add(v.getTotal_venta());
               ventasTotales = ventasTotales.add(v.getTotal_venta());
           }else{
               ventasTotales = ventasTotales.add(v.getTotal_venta());
           }     
        }
        lblVentasDiarias.setText("Q "+ ventasDeHoy.toPlainString());
        lblVentasTotales.setText("Q "+ ventasTotales.toPlainString());
        
        //Para total de boletos
        for(int i = 0; i < listaDetalleVentas.size(); i++){
            Venta v = listaVentas.get(i);
            DetalleVenta dV = listaDetalleVentas.get(i);
            if(fechaHoy.equals(sdf.format(v.getFecha_venta()))){
                totalBoletos += dV.getCantidad();
            }
        }
        
        lblBoletosDiarios.setText(String.valueOf(totalBoletos));
    }
    
    private void setUserPhoto(String username) {
        username = username.trim().toLowerCase();
        String path = "";

        switch (username) {
            case "erick":
                path = "/PalomoFormal.jpeg";
                break;
            case "cindy":
                path = "/CindyFace.jpeg";
                break;
            case "fernando":
                path = "/JoseFace.jpeg";
                break;
            case "jorge":
                path = "/Bandera Argentina.png";
                break;
            default:
                path = "/AzulGuate.png";
        }

        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
            java.awt.Image image = icon.getImage().getScaledInstance(
                    LabelFotoUsuario.getWidth(),
                    LabelFotoUsuario.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
            );
            LabelFotoUsuario.setIcon(new javax.swing.ImageIcon(image));
        } else {
            System.err.println("❌ Imagen no encontrada: " + path);
        }
    }
}
