/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;

import com.boletos.boletosapiu.model.DetalleVenta;
import com.boletos.boletosapiu.model.Inventario;
import com.boletos.boletosapiu.model.Partido;
import com.boletos.boletosapiu.model.Venta;
import com.boletos.boletosapiu.service.DetalleVentaService;
import com.boletos.boletosapiu.service.InventarioService;
import com.boletos.boletosapiu.service.VentaService;
import java.awt.Image;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author josef
 */
public class ConfimacionDeVenta extends javax.swing.JPanel {

    VentaService serviceVenta = new VentaService();
    DetalleVentaService serviceDetalle = new DetalleVentaService();
    InventarioService serviceInventario = new InventarioService();
    
    private mainPanel mainFrame;
    Partido partido;
    Venta venta;
    DetalleVenta detalle;
    Inventario inventario;
    String banco;
    
    /**
     * Creates new form ConfimacionDeVenta
     */
    public ConfimacionDeVenta() {
        initComponents();   
        }

    public ConfimacionDeVenta(mainPanel main) {
        initComponents();
        this.mainFrame = main;     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblImpuestos = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDescuento1 = new javax.swing.JLabel();
        lblDescuento2 = new javax.swing.JLabel();
        lblfede = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblNombreComprador = new javax.swing.JLabel();
        lblCorreoComprador = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTipoPartido = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPartidoLocal = new javax.swing.JLabel();
        lblVisitante = new javax.swing.JLabel();
        lblEstadio = new javax.swing.JLabel();
        lblCantidadBoletos = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        lblBanco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LabelFondoCon = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubTotal.setText("Subtotal:");

        jLabel1.setText("Descuentos:");

        lblImpuestos.setText("IVA:");

        lblTotal.setText("Total:");

        lblfede.setText("jLabel21");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfede, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescuento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDescuento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblSubTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescuento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescuento2)
                        .addGap(18, 18, 18)
                        .addComponent(lblImpuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblfede, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 753, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONFIRMAR COMPRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 394, 49));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        lblNombreComprador.setText("Nombre Comprador:");

        lblCorreoComprador.setText("Correo Comprador:");

        lblFecha.setText("Fecha:");

        lblTipoPartido.setText("Tipo Partido:");

        lblCategoria.setText("Categoria:");

        lblPartidoLocal.setText("Equipo Local:");

        lblVisitante.setText("Equipo Visitante:");

        lblEstadio.setText("Estadio:");

        lblCantidadBoletos.setText("Cantidad Boletos:");

        lblLocalidad.setText("Localidad:");

        lblTipoPago.setText("Tipo de Pago:");

        lblBanco.setText("Banco:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreComprador, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(lblCorreoComprador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoPago, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(lblBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidadBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblPartidoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComprador)
                    .addComponent(lblEstadio))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoComprador)
                    .addComponent(lblCantidadBoletos))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblLocalidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPartido)
                    .addComponent(lblTipoPago))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblBanco))
                .addGap(18, 18, 18)
                .addComponent(lblPartidoLocal)
                .addGap(18, 18, 18)
                .addComponent(lblVisitante)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-30.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Estimado cliente, por favor verifique que sus datos sean los correctos antes de confirmar su compra:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 735, -1));

        jLabel23.setBackground(new java.awt.Color(0, 153, 153));
        jLabel23.setOpaque(true);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 840, 30));

        jLabel24.setBackground(new java.awt.Color(0, 153, 153));
        jLabel24.setOpaque(true);
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 830, 480));

        LabelFondoCon.setText("jLabel26");
        jPanel1.add(LabelFondoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1140, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Venta ventaCreada;
        try {
            ventaCreada = serviceVenta.createVenta(venta);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            return;
        }

        detalle.setId_venta(ventaCreada.getId_venta());
        try{
            serviceDetalle.createDetalleVenta(detalle);
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            return;
        }
        
        inventario.setCantidad_disponible(inventario.getCantidad_disponible() - detalle.getCantidad());
        try {
            serviceInventario.updateInventario(inventario.getId_inventario(), inventario);
    
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            return;
        } 
    
        VentaConfirmada ventaRealizada = new VentaConfirmada();
        JOptionPane.showMessageDialog(this, ventaRealizada, "Venta registrada", 1);
        mainFrame.ShowPanel("VendedorApp");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        mainFrame.ShowPanel("panelVentas");
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondoCon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCorreoComprador;
    private javax.swing.JLabel lblDescuento1;
    private javax.swing.JLabel lblDescuento2;
    private javax.swing.JLabel lblEstadio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblNombreComprador;
    private javax.swing.JLabel lblPartidoLocal;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JLabel lblTipoPartido;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVisitante;
    private javax.swing.JLabel lblfede;
    // End of variables declaration//GEN-END:variables

    public void loadConfirmacionVenta(Inventario inv, Partido partidoE, Venta ventaC, DetalleVenta detalleC, String bancoE, String nombreLocalidad, BigDecimal subTotal){
        partido = partidoE;
        venta = ventaC;
        detalle = detalleC;
        banco = bancoE;
        inventario = inv;
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
        Date now = new Date();
        
        SwingUtilities.invokeLater(() -> {
        setImageLabel(lblfede, "/Fedefut.png");
        setImageLabel(LabelFondoCon, "/sintitulo.png");
        });
        
        lblNombreComprador.setText("Nombre del comprador: "+venta.getNombre_comprador());
        lblCorreoComprador.setText("Correo del comprador: "+venta.getCorreo_comprador());
        lblFecha.setText("Fecha: " + sdf.format(now));
        lblTipoPartido.setText("Tipo partido: " + partido.getTipo_partido());
        lblCategoria.setText("Categoria: " + partido.getCategoria());
        lblPartidoLocal.setText("Equipo local: " + partido.getEquipo_local());
        lblVisitante.setText("Equipo visitante: " + partido.getEquipo_visitante());
        lblEstadio.setText("Estadio: " + partido.getEstadio());
        lblCantidadBoletos.setText("Cantidad de boletos: " + detalle.getCantidad());
        lblLocalidad.setText("Localidad: " + nombreLocalidad);
        lblTipoPago.setText("Tipo pago: " + venta.getTipo_pago());
        lblBanco.setText("Banco: " + banco);
        
        lblSubTotal.setText("Subtotal: Q " + subTotal);
        BigDecimal IVA = new BigDecimal("0.12");
        BigDecimal descuentoInicioPartido = new BigDecimal("0.5");
        BigDecimal descuentoBanco = new BigDecimal("0.05");
        BigDecimal descuento1 = BigDecimal.ZERO;
        BigDecimal descuento2 = BigDecimal.ZERO;

        BigDecimal tempAmount = subTotal;

        if(partido.getEstado().equals("En Curso")){
            BigDecimal discount = tempAmount.multiply(descuentoInicioPartido)
                    .setScale(2, RoundingMode.HALF_UP);
            tempAmount = tempAmount.subtract(discount);
            descuento1 = discount;
            lblDescuento1.setText("Partido en curso. -Q" + discount);
        }else{
            lblDescuento1.setText("");
        }

        if(banco.equals("BAC Credomatic")){
            BigDecimal discount = tempAmount.multiply(descuentoBanco)
                    .setScale(2, RoundingMode.HALF_UP);
            tempAmount = tempAmount.subtract(discount);
            descuento2 = discount;
            lblDescuento2.setText("Banco afiliado. -Q " + discount);
        }else{
            
            lblDescuento2.setText("");
        }

        BigDecimal impuestos = tempAmount.multiply(IVA)
                .setScale(2, RoundingMode.HALF_UP);

        lblImpuestos.setText("IVA. +Q " + impuestos);
        BigDecimal total = tempAmount.add(impuestos);
        lblTotal.setText("Total: " + total);
        BigDecimal descuentoTotal = descuento1.add(descuento2);
        
        venta.setTotal_venta(total);
        detalle.setDescuento(descuentoTotal);
               
    }
    
    private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
        java.net.URL imgURL = getClass().getResource(resourcePath);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            Image img = icon.getImage().getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(img));
        } else {
            System.err.println("❌ No se encontró la imagen: " + resourcePath);
        }
    }
}
