/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;

import com.boletos.boletosapiu.model.DetalleVenta;
import com.boletos.boletosapiu.model.Venta;
import com.boletos.boletosapiu.service.DetalleVentaService;
import com.boletos.boletosapiu.service.VentaService;
import com.boletos.boletosapiu.utils.CustomScrollBarUI;
import com.boletos.boletosapiu.utils.GradientPanelBoletos;
import java.awt.Image;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMD 5600G
 */
public class CRUDVenta extends javax.swing.JPanel {

    private mainPanel mainFrame;
    
    DefaultTableModel model;
    
    VentaService serviceVenta = new VentaService();
    DetalleVentaService serviceDetalle = new DetalleVentaService();
    
    List<Venta> listaVentas;
    List<DetalleVenta> listaDetalle;
    /**
     * Creates new form CRUDVenta
     */
    public CRUDVenta() {
        initComponents();
    }
    
    public CRUDVenta(mainPanel main) {
        initComponents();
        this.mainFrame = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new GradientPanelBoletos(
            java.awt.Color.decode("#A1A1B5"),  // color 1
            java.awt.Color.decode("#062857")   // color 2
        );
        scrollModificar = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btnActualizarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spnPrimeraFecha = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnSegundaFecha = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoPagoFiltro = new javax.swing.JComboBox<>();
        btnFiltros = new javax.swing.JButton();
        txtNombreComprador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreoComprador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoPago = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        spnTotalVenta = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spnCantidadBoletos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnPrecioU = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnDescuento = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelLogo2 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollModificar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel31.setBackground(new java.awt.Color(2, 30, 69));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Ventas Realizadas");
        jLabel31.setOpaque(true);

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVentas);

        jLabel32.setBackground(new java.awt.Color(2, 30, 69));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Editar Venta");
        jLabel32.setOpaque(true);

        jLabel33.setText("Nombre del comprador:");

        jLabel40.setBackground(new java.awt.Color(2, 30, 69));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Detalle de la Venta");
        jLabel40.setOpaque(true);

        btnActualizarVenta.setText("Modificar Venta");
        btnActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde:");

        spnPrimeraFecha.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setText("Hasta:");

        spnSegundaFecha.setModel(new javax.swing.SpinnerDateModel());

        jLabel3.setText("Tipo de Pago:");

        cmbTipoPagoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Efectivo", "Tarjeta Credito" }));

        btnFiltros.setText("Filtrar");
        btnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrosActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo del comprador:");

        jLabel5.setText("Tipo de pago:");

        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta Credito" }));

        jLabel6.setText("Total de la venta:");

        spnTotalVenta.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel7.setText("Cantidad de boletos:");

        spnCantidadBoletos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel8.setText("Precio unitario:");

        spnPrecioU.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel11.setText("Descuento:");

        spnDescuento.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnPrimeraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnSegundaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoPagoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltros))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCorreoComprador, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtNombreComprador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnPrimeraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnSegundaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoPagoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltros))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spnTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spnCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spnPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(spnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnActualizarVenta)
                .addContainerGap())
        );

        scrollModificar.setViewportView(jPanel4);

        jPanel2.add(scrollModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 700, 530));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SISTEMA DE GESTION DE VENTAS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 660, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Federacion Nacional de Futbol de Guatemala");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        LabelLogo2.setText("jLabel11");
        jPanel2.add(LabelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 60, 70));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-30.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel2.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LabelLogo.setText("jLabel1");
        jPanel2.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 630));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
       fillFieldsFromSelectedRow();
    }//GEN-LAST:event_tblVentasMouseClicked

    private void btnActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVentaActionPerformed
        if(tblVentas.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar registro en la tabla.", "Error", 0);
            return;
        }
        
        int registro = tblVentas.getSelectedRow();
        
        Venta venta = new Venta();
        venta.setId_venta(listaVentas.get(registro).getId_venta());
        venta.setId_usuario(listaVentas.get(registro).getId_usuario());
        venta.setNombre_comprador(txtNombreComprador.getText());
        venta.setCorreo_comprador(txtCorreoComprador.getText());
        venta.setTipo_pago((String)cmbTipoPago.getSelectedItem());
        venta.setFecha_venta(listaVentas.get(registro).getFecha_venta());
        venta.setTotal_venta(BigDecimal.valueOf((double)spnTotalVenta.getValue()));
        
        DetalleVenta detalle = new DetalleVenta();
        detalle.setId_detalle(listaDetalle.get(registro).getId_detalle());
        detalle.setId_venta(listaDetalle.get(registro).getId_venta());
        detalle.setId_localidad(listaDetalle.get(registro).getId_localidad());
        detalle.setId_partido(listaDetalle.get(registro).getId_partido());
        detalle.setCantidad((int)spnCantidadBoletos.getValue());
        
        detalle.setPrecio_unitario(BigDecimal.valueOf((double)spnPrecioU.getValue()));
        detalle.setDescuento(BigDecimal.valueOf((double)spnDescuento.getValue()));
        
        crearRegistros(venta, detalle);
        
        cargarListas();      
        clearFields();
    }//GEN-LAST:event_btnActualizarVentaActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        mainFrame.ShowPanel("AdminDashboard");
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrosActionPerformed
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");  
        Date now = new Date();
        Date spn1 = (Date) spnPrimeraFecha.getValue();
        Date spn2 = (Date) spnSegundaFecha.getValue();

        boolean isSpn1Today = sdf.format(spn1).equals(sdf.format(now));
        boolean isSpn2Today = sdf.format(spn2).equals(sdf.format(now));
        int selectedType = cmbTipoPagoFiltro.getSelectedIndex();

        if ((!isSpn1Today || !isSpn2Today) && selectedType != 0) {
            for(Venta v : listaVentas){
                Date fechaVenta = v.getFecha_venta();
                String tipoPago = v.getTipo_pago();
                if(!fechaVenta.before(spn1) && !fechaVenta.after(spn2) && tipoPago.equals(cmbTipoPagoFiltro.getSelectedItem())){
                    model.addRow(new Object[]{v.getNombre_comprador(), v.getCorreo_comprador(), v.getTipo_pago(), sdf.format(v.getFecha_venta()), v.getTotal_venta()});
                }
                
            }
        } else if ((!isSpn1Today || !isSpn2Today) && selectedType == 0) {
            for(Venta v : listaVentas){
                Date fechaVenta = v.getFecha_venta();
                if(!fechaVenta.before(spn1) && !fechaVenta.after(spn2)){
                    model.addRow(new Object[]{v.getNombre_comprador(), v.getCorreo_comprador(), v.getTipo_pago(), sdf.format(v.getFecha_venta()), v.getTotal_venta()});
                }
            }
        } else if (isSpn1Today && isSpn2Today && selectedType != 0) {
            for(Venta v : listaVentas){
                String tipoPago = v.getTipo_pago();
                if(tipoPago.equals(cmbTipoPagoFiltro.getSelectedItem())){
                    model.addRow(new Object[]{v.getNombre_comprador(), v.getCorreo_comprador(), v.getTipo_pago(), sdf.format(v.getFecha_venta()), v.getTotal_venta()});
                }
            }
        }else if(isSpn1Today && isSpn2Today && selectedType == 0){
            for(Venta v : listaVentas){
                model.addRow(new Object[]{v.getNombre_comprador(), v.getCorreo_comprador(), v.getTipo_pago(), sdf.format(v.getFecha_venta()), v.getTotal_venta()});
            }
        }
        sortListas();
    }//GEN-LAST:event_btnFiltrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelLogo2;
    private javax.swing.JButton btnActualizarVenta;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JComboBox<String> cmbTipoPago;
    private javax.swing.JComboBox<String> cmbTipoPagoFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JScrollPane scrollModificar;
    private javax.swing.JSpinner spnCantidadBoletos;
    private javax.swing.JSpinner spnDescuento;
    private javax.swing.JSpinner spnPrecioU;
    private javax.swing.JSpinner spnPrimeraFecha;
    private javax.swing.JSpinner spnSegundaFecha;
    private javax.swing.JSpinner spnTotalVenta;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCorreoComprador;
    private javax.swing.JTextField txtNombreComprador;
    // End of variables declaration//GEN-END:variables

    public void cargarCRUDVenta(){
        SwingUtilities.invokeLater(() -> {
            setImageLabel(LabelLogo, "/ChatGPT Image 9 oct 2025, 03_07_12 p.m..png");
            setImageLabel(LabelLogo2, "/LOGO GUATE SELE.png");
        });
        customSpinnerDate();
        scrollModificar.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        cargarListas();
        
        model = new DefaultTableModel(new String [] {"Nombre del Comprador", "Correo del Comprador","Tipo de Pago","Fecha de la Venta","Total de la Venta"}, 0);
        tblVentas.setModel(model);
        
        cargarVentas();
    }
    
    private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
        java.net.URL imgURL = getClass().getResource(resourcePath);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            Image img = icon.getImage().getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(img));
        } else {
            System.err.println("❌ No se encontró la imagen: " + resourcePath);
        }
    }
    
    private void cargarListas(){       
        try {
            listaVentas = serviceVenta.getVentas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las ventas." + ex.getMessage(),"Error", 0);
        }
        
        try {
            listaDetalle = serviceDetalle.getDetalleVentas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los detalles de venta." + ex.getMessage(),"Error", 0);
        }
        
        sortListas();
    }
    
    private void sortListas(){
        listaVentas.sort((id1, id2) -> Integer.compare(id1.getId_venta(), id2.getId_venta()));
        listaDetalle.sort((id1, id2) -> Integer.compare(id1.getId_detalle(), id2.getId_detalle()));
    }
    
    private void cargarVentas(){
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        for(Venta v : listaVentas){
            model.addRow(new Object[]{v.getNombre_comprador(), v.getCorreo_comprador(), v.getTipo_pago(), sdf.format(v.getFecha_venta()), v.getTotal_venta()});
        }
    }
    
    private void fillFieldsFromSelectedRow() {
        int row = tblVentas.getSelectedRow();
        txtNombreComprador.setText(listaVentas.get(row).getNombre_comprador());
        txtCorreoComprador.setText(listaVentas.get(row).getCorreo_comprador());
        cmbTipoPago.setSelectedItem(listaVentas.get(row).getTipo_pago());
        spnTotalVenta.setValue(listaVentas.get(row).getTotal_venta().doubleValue());
        
        spnCantidadBoletos.setValue(listaDetalle.get(row).getCantidad());
        spnPrecioU.setValue(listaDetalle.get(row).getPrecio_unitario().doubleValue());
        spnDescuento.setValue(listaDetalle.get(row).getDescuento().doubleValue());
    }
    
    private void customSpinnerDate(){
        spnPrimeraFecha.setModel(new SpinnerDateModel());
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(spnPrimeraFecha, "dd-MM-yyyy");
        spnPrimeraFecha.setEditor(dateEditor);
        
        spnSegundaFecha.setModel(new SpinnerDateModel());
        JSpinner.DateEditor dateEditor2 = new JSpinner.DateEditor(spnSegundaFecha, "dd-MM-yyyy");
        spnSegundaFecha.setEditor(dateEditor2);
    }
    
    private void crearRegistros(Venta venta, DetalleVenta detalle){
        try {
            serviceVenta.updateVenta(venta.getId_venta(), venta);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la venta." + ex.getMessage(), "Error", 0);
            return;
        }
        
        try{
            serviceDetalle.updateDetalleVenta(detalle.getId_detalle(), detalle);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el detalle de venta." + ex.getMessage(), "Error", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Venta actualizada correctamente!");
    }
    
    private void clearFields(){
        txtNombreComprador.setText("");
        txtCorreoComprador.setText("");
        spnTotalVenta.setValue(0);
        spnCantidadBoletos.setValue(0);
        spnPrecioU.setValue(0);
        spnDescuento.setValue(0);
    }
}
