package com.boletos.boletosapiu.views;
import com.boletos.boletosapiu.utils.GradientPanelBoletos;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import com.boletos.boletosapiu.model.Usuario;
import com.boletos.boletosapiu.service.UsuarioService;
import javax.swing.JOptionPane;
import com.boletos.boletosapiu.utils.Encriptacion;
import java.security.NoSuchAlgorithmException;

public class LoginView extends javax.swing.JFrame {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());
    
    //Declaración de objetos para importar funciones
    UsuarioService service = new UsuarioService();
    Encriptacion encriptar = new Encriptacion();
    
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
         this.setLocationRelativeTo(null);
     //foto
     setImageLabel(LabelLogin, "/ChatGPT Image 19 oct 2025, 12_41_28 a.m..png");
     setImageLabel(LabelLogo3, "/LOGO GUATE SELE.png");
     
    
}
private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
    java.net.URL imgURL = getClass().getResource(resourcePath);
    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        Image img = icon.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(img));
    } else {
        System.err.println("❌ No se encontró la imagen: " + resourcePath);
    }
}
    private boolean login(String username, String password){
        Usuario user = null;
        try{
            user = service.loginUsuario(username);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + ex.getMessage());
        }
        
        if(validarUsuario(user, password)){
            JOptionPane.showMessageDialog(this, "Se inició sesión! Usuario:" + user.toString());
            return true;
        }else{
            JOptionPane.showMessageDialog(this, "Error al iniciar sesión.");
            return false;
        }    
    }
    
    private boolean validarUsuario(Usuario user, String password){
        /* if(user.isActive()){     
        } */

        if(user == null){
            System.out.println("Usuario = null");
            return false;
        }
        if(!user.getContrasena_hash().equals(password)){
            lblClaveMensaje.setText("Contraseña incorrecta");
            return false;
        }
        
       return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new GradientPanelBoletos(
            Color.decode("#646482"),
            Color.decode("#062857"));
        pnlLoginInfo = new com.boletos.boletosapiu.utils.RoundedGradientPanelBoletos(
            40,
            new java.awt.Color(15, 15, 15, 150),  // negro superior (muy oscuro)
            new java.awt.Color(35, 35, 35, 150)   // negro inferior (un poco más claro)
        );
        lblTituloLogin = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblCorreoMensaje = new javax.swing.JLabel();
        lblClaveMensaje = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblShowHidePassword = new javax.swing.JLabel();
        LabelLogo3 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setPreferredSize(new java.awt.Dimension(970, 700));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoginInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginInfo.setOpaque(false);

        lblTituloLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLogin.setText("Iniciar Sesión");

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Nombre de Usuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });

        lblCorreoMensaje.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCorreoMensaje.setForeground(new java.awt.Color(255, 51, 51));

        lblClaveMensaje.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblClaveMensaje.setForeground(new java.awt.Color(255, 51, 51));

        btnLogin.setBackground(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Contraseña");
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        lblShowHidePassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblShowHidePassword.setForeground(new java.awt.Color(255, 255, 255));
        lblShowHidePassword.setText("Mostrar");
        lblShowHidePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblShowHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowHidePasswordMouseClicked(evt);
            }
        });

        LabelLogo3.setText("jLabel1");

        javax.swing.GroupLayout pnlLoginInfoLayout = new javax.swing.GroupLayout(pnlLoginInfo);
        pnlLoginInfo.setLayout(pnlLoginInfoLayout);
        pnlLoginInfoLayout.setHorizontalGroup(
            pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                .addGroup(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                                .addGroup(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(lblCorreoMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblShowHidePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClaveMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(LabelLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlLoginInfoLayout.setVerticalGroup(
            pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LabelLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloLogin)
                .addGap(26, 26, 26)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowHidePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClaveMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pnlBackground.add(pnlLoginInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 530, 440));

        LabelLogin.setText("jLabel1");
        pnlBackground.add(LabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(txtUsuario.getText().equals("Nombre de Usuario")){
            lblCorreoMensaje.setText("Ingrese nombre de usuario");
            return;
        }
        if(new String(txtPassword.getPassword()).equals("Contraseña")){
            lblClaveMensaje.setText("Ingrese contraseña");
            return;
        }
        
        String user = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String hashPassword = null;
        try {
            hashPassword = encriptar.hashMD5(password);
        } catch (NoSuchAlgorithmException ex) {
            System.getLogger(LoginView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        login(user, password);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if("Nombre de Usuario".equals(txtUsuario.getText())){
            txtUsuario.setText("");
            txtUsuario.setForeground(new Color(255,255,255));
        }
        lblCorreoMensaje.setText("");
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if("".equals(txtUsuario.getText())){
            txtUsuario.setText("Nombre de Usuario");
            txtUsuario.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if("Contraseña".equals(String.valueOf(txtPassword.getPassword()))){
            txtPassword.setText("");
            txtPassword.setForeground(new Color(255,255,255));
            if(txtPassword.getEchoChar()=='\u0000' && lblShowHidePassword.getText().equals("Mostrar")){
                txtPassword.setEchoChar('\u2022');
            }
        }
        lblClaveMensaje.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void lblShowHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHidePasswordMouseClicked
        if(lblShowHidePassword.getText().equals("Mostrar")){
            lblShowHidePassword.setText("Ocultar");
            txtPassword.setEchoChar('\u0000');
            
        }else{
            lblShowHidePassword.setText("Mostrar");
            txtPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_lblShowHidePasswordMouseClicked

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if("".equals(String.valueOf(txtPassword.getPassword()))){
            txtPassword.setText("Contraseña");
            txtPassword.setForeground(new Color(153,153,153));
            if(txtPassword.getEchoChar()=='\u2022' && !lblShowHidePassword.getText().equals("Ocultar")){
                txtPassword.setEchoChar('\u0000');
            }
        }
    }//GEN-LAST:event_txtPasswordFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogo3;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblClaveMensaje;
    private javax.swing.JLabel lblCorreoMensaje;
    private javax.swing.JLabel lblShowHidePassword;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlLoginInfo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
