/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.boletos.boletosapiu.views;

import com.boletos.boletosapiu.model.DetalleVenta;
import com.boletos.boletosapiu.model.Partido;
import com.boletos.boletosapiu.model.Usuario;
import com.boletos.boletosapiu.model.Venta;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author AMD 5600G
 */
public class mainPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainPanel.class.getName());
    private CardLayout cardLayout;
    private JPanel cardPanel;
    
    LoginPanel login = new LoginPanel(this);
    AdminDashboardPanel adminDashboard = new AdminDashboardPanel(this);
    PartidosPanelesPanel vendedorApp = new PartidosPanelesPanel(this);
    InventariosPanel inventarioPanel = new InventariosPanel(this);
    AdminResumenVentasPanel resumenPanel = new AdminResumenVentasPanel(this);
    UsuariosPanel usuariosPanel = new UsuariosPanel(this);
    PartidosPanel partidosPanel = new PartidosPanel(this);
    VentasPanel panelVentas = new VentasPanel(this);
    
    /**
     * Creates new form mainPanel
     */
    public mainPanel(){
        initComponents();
       
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        cardPanel.add(login, "login");
        cardPanel.add(adminDashboard, "AdminDashboard");
        cardPanel.add(vendedorApp, "VendedorApp");
        cardPanel.add(inventarioPanel, "InventarioApp");
        cardPanel.add(resumenPanel, "PanelResumenVentas");
        cardPanel.add(usuariosPanel, "UsuariosPanel");
        cardPanel.add(partidosPanel, "partidosPanel");
        cardPanel.add(panelVentas, "panelVentas");
        
        setContentPane(cardPanel);
        cardLayout.show(cardPanel, "login");
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            new mainPanel().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void loadAdminDashboard(Usuario user){
        adminDashboard.cargarAdminDashboard(user);
        cardLayout.show(cardPanel, "AdminDashboard");
    }
    
    public void loadVendedorApp(){
        vendedorApp.cargarPartidos();
        cardLayout.show(cardPanel, "VendedorApp");
    }
    
    public void loadDetalleVenta(List<Venta> listVenta, List<DetalleVenta> listDetalleVenta, List<Partido> listPartidos){
        resumenPanel.loadAdminResumenVentas(listVenta, listDetalleVenta, listPartidos);
        cardLayout.show(cardPanel, "PanelResumenVentas");
    }
    
    public void loadUsuariosPanel(){
        usuariosPanel.cargarUsuariosPanel();
        cardLayout.show(cardPanel, "UsuariosPanel");
    }
    
    public void loadPartidosPanel(){
        partidosPanel.cargarPartidosPanel();
        cardLayout.show(cardPanel, "partidosPanel");
    }
    
    public void loadPanelVentas(Partido partido){
        panelVentas.cargarPanelVentas(partido);
        cardLayout.show(cardPanel, "panelVentas");
    }
    
    public void ShowPanel(String panelName){
        cardLayout.show(cardPanel, panelName);
    }
}
