/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author josef
 */
public class PanelPartidos extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    
    public PanelPartidos() {
        initComponents();
     //   Bandera1.setIcon(new ImageIcon(getClass().getResource("/Bandera Guatemala.jpg")));
      //  Bandera1.setText("prueba");
        SwingUtilities.invokeLater(() -> {
        setImageLabel(Bandera1, "/Bandera Guatemala.jpg");
        setImageLabel(Bandera2, "/Bandera Colombia.jpg");
        setImageLabel(Mundialfondo, "/fondoahorano.png");
    });
        
     //foto
        //setImageLabel(Bandera1, "/Bandera Guatemala.jpg");
     //setImageLabel(, "/Bandera Colombia.jpg");
        
    }
private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
    java.net.URL imgURL = getClass().getResource(resourcePath);
    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        Image img = icon.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(img));
    } else {
        System.err.println("❌ No se encontró la imagen: " + resourcePath);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Bandera1 = new javax.swing.JLabel();
        Bandera2 = new javax.swing.JLabel();
        Mundialfondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setText("jLabel1");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 10, 90, 30));

        jButton1.setText("ENTRADAS");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        Bandera1.setText("jLabel1");
        jPanel1.add(Bandera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 100));

        Bandera2.setText("jLabel1");
        jPanel1.add(Bandera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 100));

        Mundialfondo.setText("j");
        jPanel1.add(Mundialfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bandera1;
    private javax.swing.JLabel Bandera2;
    private javax.swing.JLabel Mundialfondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
