/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;

import com.boletos.boletosapiu.utils.RoundedGradientPanelBoletos;
import com.boletos.boletosapiu.utils.GradientPanelBoletos;
import java.awt.Image;
import javax.swing.ImageIcon;
import com.boletos.boletosapiu.service.PartidoService;
import com.boletos.boletosapiu.model.Partido;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author AMD 5600G
 */
public class PartidosPanelesPanel extends javax.swing.JPanel {

    private mainPanel mainFrame;
    
    PartidoService service = new PartidoService();
    List<Partido> listaPartidos;
    
    /**
     * Creates new form PartidosPanelesPanel
     */
    
    public PartidosPanelesPanel(){
        initComponents();    
        SwingUtilities.invokeLater(() -> {
            setImageLabel(LabelSele, "/camisolon.png");
            setImageLabel(Cerrar, "/log-out-30.png");
        });
        
        pnlPartidosMayor.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
    }
    
    public PartidosPanelesPanel(mainPanel main){
        initComponents();
        this.mainFrame = main;
     
        SwingUtilities.invokeLater(() -> {
            setImageLabel(LabelSele, "/camisolon.png");
        });
        
        pnlPartidosMayor.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new GradientPanelBoletos(
            java.awt.Color.decode("#30333D"), // color 1
            java.awt.Color.decode("#33394F")  // color 2
        );
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        LabelSele = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPartidosMayor = new GradientPanelBoletos(
            java.awt.Color.decode("#B0B0B5"), // color 1
            java.awt.Color.decode("#DADAF2")  // color 2
        );
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlPartidosSub17 = new GradientPanelBoletos(
            java.awt.Color.decode("#B0B0B5"), // color 1
            java.awt.Color.decode("#DADAF2")  // color 2
        );
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlPartidosFutsal = new GradientPanelBoletos(
            java.awt.Color.decode("#B0B0B5"), // color 1
            java.awt.Color.decode("#DADAF2")  // color 2
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        Cerrar.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 60, 630));

        LabelSele.setText("jLabel1");
        jPanel2.add(LabelSele, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 630));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Partidos Mayor");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Partidos Sub 17 ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Partidos Futsal");

        pnlPartidosMayor.setLayout(new javax.swing.BoxLayout(pnlPartidosMayor, javax.swing.BoxLayout.X_AXIS));
        jScrollPane1.setViewportView(pnlPartidosMayor);

        pnlPartidosSub17.setLayout(new javax.swing.BoxLayout(pnlPartidosSub17, javax.swing.BoxLayout.X_AXIS));
        jScrollPane2.setViewportView(pnlPartidosSub17);

        pnlPartidosFutsal.setLayout(new javax.swing.BoxLayout(pnlPartidosFutsal, javax.swing.BoxLayout.X_AXIS));
        jScrollPane3.setViewportView(pnlPartidosFutsal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(514, 514, 514)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 602, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel LabelSele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlPartidosFutsal;
    private javax.swing.JPanel pnlPartidosMayor;
    private javax.swing.JPanel pnlPartidosSub17;
    // End of variables declaration//GEN-END:variables

    private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
        java.net.URL imgURL = getClass().getResource(resourcePath);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            Image img = icon.getImage().getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(img));
        } else {
            System.err.println("❌ No se encontró la imagen: " + resourcePath);
        }
    }
    
    public void cargarPartidos(){
        try {
            listaPartidos = service.getPartidos();
        } catch (Exception ex) {
            System.getLogger(PartidosPanelesPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        for(Partido p : listaPartidos){
           if(!p.getEstado().equals("Finalizado")){                         
                if(p.getCategoria().equals("Mayor")){
                    PanelPartidos panel = new PanelPartidos(p.getEquipo_local(),p.getEquipo_visitante());
                    pnlPartidosMayor.add(panel);
                    pnlPartidosMayor.add(Box.createRigidArea(new Dimension(10,0)));
                }
                if(p.getCategoria().equals("Sub 17")){
                    PanelPartidos panel = new PanelPartidos(p.getEquipo_local(),p.getEquipo_visitante());
                    pnlPartidosSub17.add(panel);
                    pnlPartidosSub17.add(Box.createRigidArea(new Dimension(10,0)));
                }
                if(p.getCategoria().equals("Futsal")){
                    PanelPartidos panel = new PanelPartidos(p.getEquipo_local(),p.getEquipo_visitante());
                    pnlPartidosFutsal.add(panel);
                    pnlPartidosFutsal.add(Box.createRigidArea(new Dimension(10,0)));
                }
           }
        }
    }
}
