/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boletos.boletosapiu.views;

import com.boletos.boletosapiu.model.Usuario;
import com.boletos.boletosapiu.service.UsuarioService;
import com.boletos.boletosapiu.utils.Encriptacion;
import com.boletos.boletosapiu.utils.GradientPanelBoletos;
import com.boletos.boletosapiu.utils.RoundedGradientPanelBoletos;
import java.awt.Color;
import java.awt.Image;
import java.security.NoSuchAlgorithmException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMD 5600G
 */
public class UsuariosPanel extends javax.swing.JPanel {
    private DefaultTableModel model;
    private mainPanel mainFrame;
    List<Usuario> listaUsuarios;
    UsuarioService service = new UsuarioService();
    Encriptacion encriptar = new Encriptacion();
    /**
     * Creates new form UsuariosPanel
     */
    public UsuariosPanel() {
        initComponents();
    }

    public UsuariosPanel(mainPanel main) {
        initComponents();
        this.mainFrame = main;      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientPanelBoletos(
            java.awt.Color.decode("#646482"),  // color 1
            java.awt.Color.decode("#062857")   // color 2
        );
        tabPane = new javax.swing.JTabbedPane();
        jPanel2 = new RoundedGradientPanelBoletos(
            50,
            java.awt.Color.decode("#E6E6E8"),  // color 1
            java.awt.Color.decode("#FAFCFF")   // color 2
        );
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        lblMsgNombre = new javax.swing.JLabel();
        lblMsgUsername = new javax.swing.JLabel();
        lblMsgPassword1 = new javax.swing.JLabel();
        lblMsgPassword2 = new javax.swing.JLabel();
        jPanel3 = new RoundedGradientPanelBoletos(
            50,
            java.awt.Color.decode("#E6E6E8"),  // color 1
            java.awt.Color.decode("#FAFCFF")   // color 2
        );
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtConsultaPassword = new javax.swing.JTextField();
        txtConsultaNombreCompleto = new javax.swing.JTextField();
        txtConsultaUsername = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        cmbConsultaRol = new javax.swing.JComboBox<>();
        lblFechaCreacion = new javax.swing.JLabel();
        rbtnEstado = new javax.swing.JRadioButton();
        btnActualizar = new javax.swing.JButton();
        lblMensajeRol = new javax.swing.JLabel();
        lblMensajeNombre = new javax.swing.JLabel();
        lblMensajeUsername = new javax.swing.JLabel();
        lblMensajeID = new javax.swing.JLabel();
        logn = new RoundedGradientPanelBoletos(
            50,
            java.awt.Color.decode("#A1A6AD"),  // color 1
            java.awt.Color.decode("#021E45")   // color 2
        );
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Registro de Nuevo Usuario");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre completo:");

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre completo");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Rol:");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nombre de Usuario:");

        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.setText("Ingrese el nombre de nuevo usuario");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña:");

        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Confirme su contraseña:");

        txtConfirmPassword.setEchoChar('\u0000');
        txtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFocusGained(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 153));
        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblMsgNombre.setForeground(new java.awt.Color(255, 51, 51));
        lblMsgNombre.setPreferredSize(new java.awt.Dimension(37, 16));

        lblMsgUsername.setForeground(new java.awt.Color(255, 51, 51));
        lblMsgUsername.setPreferredSize(new java.awt.Dimension(37, 16));

        lblMsgPassword1.setForeground(new java.awt.Color(255, 51, 51));
        lblMsgPassword1.setPreferredSize(new java.awt.Dimension(37, 16));

        lblMsgPassword2.setForeground(new java.awt.Color(255, 51, 51));
        lblMsgPassword2.setPreferredSize(new java.awt.Dimension(37, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                .addComponent(lblMsgNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                .addComponent(lblMsgPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                .addComponent(lblMsgUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtConfirmPassword)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                .addComponent(lblMsgPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        tabPane.addTab("Registro", jPanel2);

        jPanel3.setOpaque(false);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel8.setText("ID:");

        jLabel9.setText("Username:");

        jLabel10.setText("Cambiar contraseña:");

        jLabel11.setText("Nombre completo:");

        jLabel12.setText("Rol:");

        jLabel13.setText("Fecha de creación:");

        jLabel14.setText("Estado:");

        cmbConsultaRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Vendedor", "Administrador" }));

        lblFechaCreacion.setText("--");

        rbtnEstado.setText("--");
        rbtnEstado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnEstadoStateChanged(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 102, 153));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblMensajeRol.setForeground(new java.awt.Color(255, 51, 51));
        lblMensajeRol.setPreferredSize(new java.awt.Dimension(43, 16));

        lblMensajeNombre.setForeground(new java.awt.Color(255, 51, 51));

        lblMensajeUsername.setForeground(new java.awt.Color(255, 51, 51));

        lblMensajeID.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblMensajeID, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(97, 97, 97)
                                            .addComponent(cmbConsultaRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(10, 10, 10))
                                        .addComponent(lblMensajeRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel14))
                                            .addGap(26, 26, 26)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbtnEstado)))
                                        .addComponent(lblMensajeUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMensajeNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtConsultaUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtConsultaPassword))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtConsultaNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtConsultaUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtConsultaNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtConsultaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbConsultaRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblFechaCreacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rbtnEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPane.addTab("Consulta / Actualizar", jPanel3);

        jPanel1.add(tabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 610));

        logn.setOpaque(false);

        LabelLogo.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de gestion de usuarios");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-30.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lognLayout = new javax.swing.GroupLayout(logn);
        logn.setLayout(lognLayout);
        lognLayout.setHorizontalGroup(
            lognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lognLayout.createSequentialGroup()
                .addContainerGap(754, Short.MAX_VALUE)
                .addGroup(lognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lognLayout.createSequentialGroup()
                        .addGroup(lognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lognLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lognLayout.createSequentialGroup()
                        .addComponent(lblBack)
                        .addContainerGap())))
        );
        lognLayout.setVerticalGroup(
            lognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lognLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack)
                .addGap(54, 54, 54)
                .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(logn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1080, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if(txtNombre.getText().equals("Ingrese su nombre completo")){
            txtNombre.setText("");
            lblMsgNombre.setText("");
            txtNombre.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if(txtUsername.getText().equals("Ingrese el nombre de nuevo usuario")){
            txtUsername.setText("");
            lblMsgUsername.setText("");
            txtUsername.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if(txtUsername.getText().equals("")){
            txtUsername.setText("Ingrese el nombre de nuevo usuario");
            txtUsername.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        lblMsgPassword1.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFocusGained
        lblMsgPassword2.setText("");
    }//GEN-LAST:event_txtConfirmPasswordFocusGained

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(txtNombre.getText().equals("Ingrese su nombre completo") || txtNombre.getText().equals("")){
            lblMsgNombre.setText("Ingrese nombre completo");
            return;
        }
        if(txtUsername.getText().equals("Ingrese el nombre de nuevo usuario") || txtUsername.getText().equals("")){
            lblMsgUsername.setText("Ingrese nombre de usuario");
            return;
        }
        if(new String(txtPassword.getPassword()).equals("")){
            lblMsgPassword1.setText("Ingrese contraseña");
            return;
        }
        if(!new String(txtPassword.getPassword()).equals(new String(txtConfirmPassword.getPassword()))){
            lblMsgPassword2.setText("Las contraseñas no coinciden!");
            return;
        }
        
        String username = txtUsername.getText().trim();
        List<Usuario> listaUsuarios;
        
        try {
            listaUsuarios = service.getUsuarios();
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + ex.getMessage());
           return;
        }
        
        for(Usuario u : listaUsuarios){
            if(u.getNombre_usuario().equals(username)){
                JOptionPane.showMessageDialog(this, "El nombre de usuario: " + username + " ya está registrado.");
                return;
            }
        }
        
        String nombreCompleto = txtNombre.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String rol = (String) cmbRol.getSelectedItem();
        Date fechaCreacion = new Date();
        Boolean estado = true;
        
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setNombre_usuario(username);
        nuevoUsuario.setNombre_completo(nombreCompleto);
        try{
            String hashPassword = encriptar.hashMD5(password);
            nuevoUsuario.setContrasena_hash(hashPassword);
        }catch (NoSuchAlgorithmException ex) {
            System.out.print(ex.getMessage());
        }
        nuevoUsuario.setRol(rol);
        nuevoUsuario.setFecha_creacion(fechaCreacion);
        nuevoUsuario.setEstado(estado);
        
        try{
           Usuario user = service.createUsuario(nuevoUsuario);
           System.out.println(nuevoUsuario.toString());
           System.out.println(user.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al crear el usuario: " + ex.getMessage());
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito!");
        clearFields();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        mainFrame.ShowPanel("AdminDashboard");
    }//GEN-LAST:event_lblBackMouseClicked

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        switch(tabPane.getSelectedIndex()){
            case 1 -> {
                loadUsuariosTable();
            }
        }
    }//GEN-LAST:event_tabPaneStateChanged

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        fillFieldsFromSelectedRow();
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String username = txtConsultaUsername.getText();
        
        if(txtID.getText().equals("")){
            lblMensajeID.setText("Debe llenar el campo de ID");
            return;
        }
        if(txtConsultaUsername.getText().equals("")){
            lblMensajeUsername.setText("Debe llenar el campo de nombre de usuario");
            return;
        }
        if(txtConsultaNombreCompleto.getText().equals("")){
            lblMensajeNombre.setText("Debe incluir nombre completo");
            return;
        }
        
        if(cmbConsultaRol.getSelectedIndex()==0){
            lblMensajeRol.setText("Debe elegir rol");
            return;
        }
        
        int selectedRow = tblUsuarios.getSelectedRow();
        if(!tblUsuarios.getValueAt(selectedRow, 1).equals(username)){
            for(int i = 0; i<tblUsuarios.getRowCount(); i++){  
                if(username.equals((String)tblUsuarios.getValueAt(i, 1))){
                JOptionPane.showMessageDialog(this, "Ese nombre de usuario ya existe");
                return;
                }
            }
        }
        
        int id = Integer.parseInt(txtID.getText());
        String password = txtConsultaPassword.getText();
        String hashPassword = "";
        
        try {
            hashPassword = encriptar.hashMD5(password);
        } catch (NoSuchAlgorithmException ex) {
            System.getLogger(UsuariosPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        String nombreCompleto = txtConsultaNombreCompleto.getText();
        String rol = (String)cmbConsultaRol.getSelectedItem();
        Date fechaCreacion = null;
        boolean estatus = rbtnEstado.isSelected();
        
        for(Usuario u : listaUsuarios){
            if(u.getId_usuario() == id){
                fechaCreacion = u.getFecha_creacion();
                if(hashPassword.equals("")){
                    hashPassword = u.getContrasena_hash();
                }
              
            }
        }
        
        Usuario user = new Usuario();
        user.setId_usuario(id);
        user.setNombre_usuario(username);    
        user.setContrasena_hash(hashPassword);
        user.setNombre_completo(nombreCompleto);
        user.setRol(rol);
        user.setFecha_creacion(fechaCreacion);
        user.setEstado(estatus);
        
        try {
            service.updateUsuario(id, user);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el usuario: " + ex.getMessage());
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito!");
        loadUsuariosTable();
        clearConsultaFields();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbtnEstadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnEstadoStateChanged
        if(rbtnEstado.isSelected()){
            rbtnEstado.setText("Activo");
        }else{
            rbtnEstado.setText("Re-Contratar");
        }
    }//GEN-LAST:event_rbtnEstadoStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbConsultaRol;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblMensajeID;
    private javax.swing.JLabel lblMensajeNombre;
    private javax.swing.JLabel lblMensajeRol;
    private javax.swing.JLabel lblMensajeUsername;
    private javax.swing.JLabel lblMsgNombre;
    private javax.swing.JLabel lblMsgPassword1;
    private javax.swing.JLabel lblMsgPassword2;
    private javax.swing.JLabel lblMsgUsername;
    private javax.swing.JPanel logn;
    private javax.swing.JRadioButton rbtnEstado;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtConsultaNombreCompleto;
    private javax.swing.JTextField txtConsultaPassword;
    private javax.swing.JTextField txtConsultaUsername;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void cargarUsuariosPanel(){
        SwingUtilities.invokeLater(() -> {
            setImageLabel(LabelLogo, "/LOGO GUATE SELE.png");
        });
        model = new DefaultTableModel(new String [] {"ID", "Username","Nombre Completo","Rol","Fecha de Creación","Estado"}, 0);
        tblUsuarios.setModel(model);
        tblUsuarios.getColumn("ID").setPreferredWidth(10);
        tblUsuarios.getColumn("Estado").setPreferredWidth(10);
    }
    
    private void setImageLabel(javax.swing.JLabel label, String resourcePath) {
        java.net.URL imgURL = getClass().getResource(resourcePath);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            Image img = icon.getImage().getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(img));
        } else {
            System.err.println("❌ No se encontró la imagen: " + resourcePath);
        }
    }
    
    private void clearFields(){
        txtNombre.setText("Ingrese su nombre completo");
        txtNombre.setForeground(new Color(204,204,204));
        txtUsername.setText("Ingrese el nombre de nuevo usuario");
        txtUsername.setForeground(new Color(204,204,204));
        txtPassword.setText("");
        txtConfirmPassword.setText("");
    }
    
    private void clearConsultaFields(){
        txtID.setText("");
        txtConsultaUsername.setText("");
        txtConsultaNombreCompleto.setText("");
        txtConsultaPassword.setText("");
        cmbConsultaRol.setSelectedIndex(0);
        lblFechaCreacion.setText("--");
        rbtnEstado.setText("--");
        rbtnEstado.setSelected(false);
    }
    
    private void loadUsuariosTable(){
        try {
            listaUsuarios = service.getUsuarios();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + ex.getMessage());
            return;
        }
        model.setRowCount(0);
        for(Usuario u : listaUsuarios){
            String status = u.isEstado() ? "✅" : "❌";
                model.addRow(new Object[]{
                    u.getId_usuario(),
                    u.getNombre_usuario(),
                    u.getNombre_completo(),
                    u.getRol(),
                    u.getFecha_creacion(),
                    status
                });
        }
    }
    
    private void fillFieldsFromSelectedRow(){
        int row = tblUsuarios.getSelectedRow();
        int id = (int) model.getValueAt(row, 0);
        txtID.setText(String.valueOf(id));
        txtConsultaUsername.setText((String) model.getValueAt(row, 1));
        txtConsultaNombreCompleto.setText((String) model.getValueAt(row, 2));
        cmbConsultaRol.setSelectedItem((String) model.getValueAt(row, 3));
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String dateValue = sdf.format((Date) model.getValueAt(row, 4));
        lblFechaCreacion.setText(dateValue);       

        if(((String)model.getValueAt(row, 5)).equals("✅")){
            rbtnEstado.setSelected(true);
            rbtnEstado.setText("Activo");
        }else{
            rbtnEstado.setSelected(false);
            rbtnEstado.setText("Re-Contratar");
        }
        
    }
}
